name: Deploy Frontend Production

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            # Carrega o NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Navega para a pasta do cliente de produção
            cd /var/www/agrosync/client
            
            # Baixa o código novo
            git pull origin main
            
            # Instala qualquer nova dependência
            npm install
            
            # Gera a build de produção
            npm run build